---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-of-model_to-be-set
  namespace: uetrajectories
  labels:
    app.kubernetes.io/name: name-of-model_to-be-set
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: name-of-model_to-be-set
  template:
    metadata:
      name: name-of-model_to-be-set
      labels:
        app.kubernetes.io/name: name-of-model_to-be-set
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '5000'
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: name-of-model-configmap_to-be-set
      containers:
      - image: name-of-model_image_to-be-set
        name: uetrajectories-model
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: to-be-set
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/config
