---
apiVersion: v1
kind: Service
metadata:
  name: name-of-model_to-be-set
  namespace: uetrajectories
  labels:
    app.kubernetes.io/name: name-of-model_to-be-set
spec:
  selector:
    app.kubernetes.io/name: upfresel-model
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
